### PR TITLE
contributing details added

### PR DESCRIPTION
**Pull request by SyedSumaimaly**
details added

### CODE REVIEW

**Comment by Jayesh-JainX** [comment]
Please change the .card6 class to .card7 in the style.css file. Additionally, Copy the original code in the index.html file from my repo and only add your details without altering any other code.

**Comment by SyedSumaimaly** [comment]
resolve style.css error.

**Comment by Jayesh-JainX** [comment]
hey @SyedSumaimaly,
you need to copy the original index.html file from my repo and paste it in your repo, and then add your details. dont do any other changes (you have changed whole index.html file, please redo that and add your details there, rest code in html file remains same)

**Comment by Jayesh-JainX** [comment]
image
 this is the error

**Comment by SyedSumaimaly** [comment]
I haven't made any changes to the index.html file in my repository, but as you instructed me, I have copied and pasted it again into my repository and pushed it. I have done it; please check.

**Comment by Jayesh-JainX** [comment]
image
the code in your index.html file is of 374, mine is 110 line code, i think your editor has formated the document automatically , use another editor or use notepad as editor.

**Comment by SyedSumaimaly** [comment]
image
Check again please..

**Comment by Jayesh-JainX** [comment]
### Before we proceed, we kindly request you to:
- Star this Repository: ⭐ Starring the repository helps us reach a wider audience and encourages more contributions. You can star the repo by clicking the "Star" button at the top of this page.

- Follow the Code of Conduct: 📜 We maintain a Code a [Code of Conduct](https://github.com/Jayesh-JainX/Hacktoberfest-23/blob/main/CONTRIBUTING.md) to ensure a positive and respectful environment for all contributors. Please review and abide by it throughout your involvement in this project.


***If you have any questions or need further assistance, feel free to ask. Happy coding! 🚀***

**Pull request merged**
