### PR TITLE
N queen solved

### PR DESCRIPTION
**Pull request by akadeepesh**

### CODE REVIEW

**Comment by Jayesh-JainX** [comment]
hi @akadeepesh,
add your details in profile, index.html and style.css file
see this [Youtube](https://www.youtube.com/watch?v=xweXYoeNkoA) video for details.

**Comment by Jayesh-JainX** [comment]
Hey @akadeepesh,
dont add two different issues in one pr.
delete the phonebook, you need to word on only assigned issue, after that you can work on other issue and submit another pr

**Comment by akadeepesh** [comment]
Done!

**Comment by Jayesh-JainX** [comment]
hi @akadeepesh,
add your details in index.html and style.css file too
see this [Youtube](https://www.youtube.com/watch?v=xweXYoeNkoA) video for details.
also mention your assigned issue number

**Comment by akadeepesh** [comment]
Added

**Comment by akadeepesh** [comment]
N queen solved #53

**Comment by Jayesh-JainX** [comment]
hi, add your details in style.css too.
the last change

**Comment by Jayesh-JainX** [comment]
hey @akadeepesh,
one last step is remaining,
add your details to style.css file, so that i can merge your pr

**Comment by akadeepesh** [comment]
All done ig

**Comment by akadeepesh** [comment]
sorry for not following the yt tutorial at once. hope you can understand :)

**Comment by Jayesh-JainX** [comment]
issue #52

**Pull request merged**
