### PR TITLE
First contribution

### PR DESCRIPTION
**Pull request by rishabhrathore055**

### CODE REVIEW

**Review by Jayesh-JainX — CHANGES_REQUESTED** [review]
the index file has large difference, please use different editor and edit code by add original code and the add your details

**Comment by rishabhrathore055** [comment]
actually, I use format Document

**Comment by Jayesh-JainX** [comment]
please dont format document keep it original and also resolve the conflicts by updating your details...

**Comment by rishabhrathore055** [comment]
Sure

**Comment by rishabhrathore055** [comment]
@Jayesh-JainX  Please check now

**Comment by rishabhrathore055** [comment]
@Jayesh-JainX  Thanks Man!

**Pull request merged**
